### ISSUE TITLE
Zero-shot evaluation

### ISSUE THREAD

**Issue by yifliu3** [BeileiCui/SurgicalDINO#1]
Hi, thanks for your great work.

Can you release the code for the inference on SCARED dataset? I'm wondering how you evaluate the relative depth generated by DINOv2.

**Comment by BeileiCui** [comment]
Hi, thanks for your questions.

I did not prepare well for the code of other parts of current supervised model. But I am going to release another version of Self-Supervised Learning method of depth estimation with more comprehensive codes including training, testing, visualization, 3d reconstruction, trained weights in the near future. So if you are still interested in it, I can recall you to it when I release it. 

In terms of evaluating depth on SCARED, we re-scale the predicted depth map by a median scaling method introduced by SfM-Leaner, which can be expressed by:

D_scaled = (D_pred * ( median(D_gt) / median(D_pred))),

where median() refers to find the median, D_gt is the ground truth depth, D_pred is predicted depth, D_scaled is re-scaled depth. Then we evaluate the performance metrics between D_scaled and D_gt.

**Comment by yifliu3** [comment]
Thanks for your prompt reply. My problems are solved and looking forward to your codes.
