### ISSUE TITLE
Can you make pretrained SurgicalDINO model public?

### ISSUE THREAD

**Issue by nanasylum** [BeileiCui/SurgicalDINO#3]
hi, thanks for your work.

Can you make pretrained SurgicalDINO model public?

**Comment by BeileiCui** [comment]
Hi thanks for your interests. I may not make the pretrained checkpoint public for now. But I am preparing for a more advanced self-supervised version for endoscopic depth estimation. Please refer to https://github.com/BeileiCui/EndoDAC. In this repo, I will prepare for the code of training, testing, visualization and also pretrained model. Please follow it if you are still interested!

**Comment by nanasylum** [comment]
ok thank u for ur suggestions!
