### ISSUE TITLE
question about why the mlp layer（FFN of the transformers of DINO） don't need Lora ? 

### ISSUE THREAD

**Issue by ripperthejack** [BeileiCui/SurgicalDINO#7]
question about why the mlp layer（FFN of the transformers of DINO） don't need Lora ?

**Comment by BeileiCui** [comment]
Hi, all the mlp-liked layers(Q,K,V,O,F1,F2) can be applied with lora. We just choose Q and V here because based on previous studies, these two layers are the most effective layer with lora. We also did lora on FFNs you may refer to EndoDAC.

**Comment by ripperthejack** [comment]
thank for quick reply
